---
output: github_document
---

<!-- NEWS.md is generated from NEWS.Rmd. Please edit that file -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# eq5d (development version)

* Added Brazilian, Canadian, Chilean, Polish and Trinidad and Tobago TTO value sets.

# eq5d 0.1.1 (2019-05-27)

* Fixed issue where displayed description values were mislabelled in the Shiny app table when the columns in the uploaded file weren't in the order MO, SC, UA, PD, AD.

* Fixed issue with Shiny app download button not working correctly.

* Added checkbox to Shiny app to give the option of displaying the index scores with all info provided in the uploaded file or just with the dimension scores.

# eq5d 0.1.0 (2019-05-10)

* Functions for calculating EQ-5D index values.

* EQ-5D-3L TTO value sets for Denmark, France, Germany, Italy, Japan, Korea, Netherlands, Spain, Thailand, UK, USA and Zimbabwe.

* EQ-5D-3L VAS value sets for Belgium, Denmark, Europe, Finland, Germany, NewZealand, Slovenia, Spain and UK.

* EQ-5D-5L VT value sets for Canada, China, England, Germany, HongKong, Indonesia, Ireland, Japan, Korea, Malaysia, Netherlands, Spain, Thailand and Uruguay.

* EQ-5D-5L Crosswalk value sets for Denmark, France, Germany, Japan, Netherlands, Spain, Thailand, UK, USA and Zimbabwe.

